version: 2.1

workflows:
  builder:
    jobs:
    - starter
    - ender: 
        requires:
            - starter

jobs: 
  starter:
    docker:
    - image: circleci/node

    steps:
    - checkout
    - run: echo "hello world ${env}"
    - run: echo "hello world2"

  ender:
    docker:
    - image: circleci/node

    steps:
    - checkout
    - run: whoami
    
