version: 2.1

executors:
  docker_container:
   docker:
      - image: circleci/node

commands:
  all_command:
    steps:
       - run: echo "hello world ${env}"
       - run: echo "hello world2 ${AUTH}"
  test:
    steps:
    - run: rm -rf node_modules
    - run: yarn install
    - run: yarn tsc
    - run: yarn test

workflows:
  builder:
    jobs:
    - starter
    

jobs: 
  starter:
    executor: docker_container

    steps:
    - checkout
    - all_command
    - test
    environment:
        AUTH : USER

 
    
