version: 2.1

executors:
  docker_container:
    - docker:
      - image: circleci/node
      
workflows:
  builder:
    jobs:
    - starter
    - ender: 
        requires:
            - starter

jobs: 
  starter:
    executor: docker_container

    steps:
    - checkout
    - run: echo "hello world ${env}"
    - run: echo "hello world2 ${AUTH}"
    environment:
        AUTH : USER

  ender:
    docker:
    - image: circleci/node

    steps:
    - checkout
    - run: whoami
    
