version: 2.1

executors:
  docker_container:
   docker:
      - image: circleci/node
      - image: circleci/mongodb

commands:
  test:
    steps:
    - run: yarn 
    - run: yarn tsc
    - run: yarn test

workflows:
  builder:
    jobs:
    - starter
    

jobs: 
  starter:
    executor: docker_container
    steps:
    - checkout
    - test
    environment:
        AUTH : USER

 
    
