version: 2.1

jobs: 
  starter:
    docker:
    - image: circleci/node

    steps:
    - checkout
    - run: echo "hello world"
    - run: echo "hello world2"

workflows:
  builder:
    jobs:
    - starter